# This is a basic workflow to help you get started with Actions

name: publish-storybook-folder-to-gh-pages-branch

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish-storybook:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Repository Checkout
        uses: actions/checkout@v2

      - name: Setup Node v14
        uses: actions/setup-node@v2
        with:
            node-version: '14'
            cache: 'npm'

      - name: Install node
        run: npm ci

      - name: Create storybook
        run: npm run build-storybook

      # Publish storybook generated in dist/ folder to gh-pages branch
      - name: Publish Storybook
        uses: maxheld83/ghpages@v0.3.0
        env:
          BUILD_DIR: dist/
          GH_PAT: ${{ secrets.GH_PAT }}
